import type { Rule } from '@/types/rule';

// 从Python版本迁移的完整默认规则数据
export const defaultRules: Rule[] = [
  {
    id: "default-1",
    code: "01.33.06.01",
    thirtyD: "N",
    matchRules: ["Confidential Disclosure Agreements", "CDA"],
    source: "default",
  },
  {
    id: "default-2",
    code: "01.33.06.02",
    thirtyD: "N",
    matchRules: ["one way letter"],
    source: "default",
  },
  {
    id: "default-3",
    code: "01.33.10.02",
    thirtyD: "N",
    matchRules: ["Privacy notice", "PN"],
    source: "default",
  },
  {
    id: "default-4",
    code: "02.02.03",
    thirtyD: "N",
    matchRules: ["FDC"],
    source: "default",
  },
  {
    id: "default-5",
    code: "02.03.03",
    thirtyD: "Y",
    matchRules: ["Local Destruction", "493847"],
    source: "default",
  },
  {
    id: "default-6",
    code: "02.03.04",
    thirtyD: "Y",
    matchRules: [" Extension Expiry Date Memo", "药品有效期延长说明"],
    source: "default",
  },
  {
    id: "default-7",
    code: "02.03.06",
    thirtyD: "Y",
    matchRules: ["Final Investigational Product Reconciliation Statement Form", "000539 "],
    source: "default",
  },
  {
    id: "default-8",
    code: "02.03.08",
    thirtyD: "N",
    matchRules: ["000541"],
    source: "default",
  },
  {
    id: "default-9",
    code: "02.03.08",
    thirtyD: "N",
    matchRules: ["081612"],
    source: "default",
  },
  {
    id: "default-10",
    code: "02.03.14",
    thirtyD: "N",
    matchRules: ["001512"],
    source: "default",
  },
  {
    id: "default-11",
    code: "02.03.15",
    thirtyD: "N",
    matchRules: ["Temperature Log"],
    source: "default",
  },
  {
    id: "default-12",
    code: "02.03.18",
    thirtyD: "N",
    matchRules: ["DV", "DPW"],
    source: "default",
  },
  {
    id: "default-13",
    code: "02.05.02",
    thirtyD: "N",
    matchRules: ["EC approval", "伦理批件"],
    source: "default",
  },
  {
    id: "default-14",
    code: "02.05.02",
    thirtyD: "N",
    matchRules: ["EC notification", "伦理意见"],
    source: "default",
  },
  {
    id: "default-15",
    code: "02.05.03",
    thirtyD: "N",
    matchRules: ["EC Member", "伦理委员会成员"],
    source: "default",
  },
  {
    id: "default-16",
    code: "02.05.03",
    thirtyD: "",
    matchRules: ["statement of compliance", "伦理委员会声明"],
    source: "default",
  },
  {
    id: "default-17",
    code: "02.05.04",
    thirtyD: "N",
    matchRules: ["EC submission letter", "伦理签收", "伦理接收", "递交信-PI to EC"],
    source: "default",
  },
  {
    id: "default-18",
    code: "02.05.04",
    thirtyD: "N",
    matchRules: ["EC applications form", "伦理申请表"],
    source: "default",
  },
  {
    id: "default-19",
    code: "02.05.04",
    thirtyD: "N",
    matchRules: ["annual report", "年度报告"],
    source: "default",
  },
  {
    id: "default-20",
    code: "02.06.01",
    thirtyD: "N",
    matchRules: ["Lab certificate", "室间质评"],
    source: "default",
  },
  {
    id: "default-21",
    code: "02.06.03",
    thirtyD: "N",
    matchRules: ["Local lab normal range", "正常值范围"],
    source: "default",
  },
  {
    id: "default-22",
    code: "02.07.03",
    thirtyD: "Y",
    matchRules: ["SEV  follow up letter"],
    source: "default",
  },
  {
    id: "default-23",
    code: "02.07.05",
    thirtyD: "Y",
    matchRules: ["SIV/RMV/FMV/SEV confirmation letter"],
    source: "default",
  },
  {
    id: "default-24",
    code: "02.07.05",
    thirtyD: "Y",
    matchRules: ["CRA transition letter"],
    source: "default",
  },
  {
    id: "default-25",
    code: "02.07.06",
    thirtyD: "N",
    matchRules: ["Site Recruitment Plan", "招募计划"],
    source: "default",
  },
  {
    id: "default-26",
    code: "02.07.08",
    thirtyD: "N",
    matchRules: ["Training Record", "培训记录"],
    source: "default",
  },
  {
    id: "default-27",
    code: "02.07.09",
    thirtyD: "N",
    matchRules: ["MV follow up letter"],
    source: "default",
  },
  {
    id: "default-28",
    code: "02.07.10",
    thirtyD: "Y",
    matchRules: ["000551", "Sponsor Visit Log", "访视登记表"],
    source: "default",
  },
  {
    id: "default-29",
    code: "02.07.12",
    thirtyD: "Y",
    matchRules: ["492536", "IIR", "Investigator Initiation Report"],
    source: "default",
  },
  {
    id: "default-30",
    code: "02.07.12",
    thirtyD: "Y",
    matchRules: ["493981", "EDC Survey", "Electronic Data Capture (EDC) Site Survey & Site IT Capability Verification Form", "501678"],
    source: "default",
  }
];
